CREATE TABLE IF NOT EXISTS symptom_analysis_history (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    patient_id BIGINT NOT NULL,
    symptoms_text TEXT NOT NULL,
    age INT NOT NULL,
    sex VARCHAR(32) NOT NULL,
    duration_hours INT NOT NULL,
    chronic_conditions_json JSON NULL,
    medications_json JSON NULL,
    allergies_json JSON NULL,
    symptom_summary TEXT NOT NULL,
    condition_categories_json JSON NOT NULL,
    urgency_level VARCHAR(20) NOT NULL,
    recommended_specialization VARCHAR(120) NOT NULL,
    red_flags_json JSON NOT NULL,
    next_step_recommendation TEXT NOT NULL,
    disclaimer TEXT NOT NULL,
    ai_provider VARCHAR(32) NOT NULL DEFAULT 'GEMINI',
    ai_model VARCHAR(64) NOT NULL,
    raw_ai_response_json JSON NULL,
    correlation_id VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    INDEX idx_symptom_history_patient_created (patient_id, created_at),
    INDEX idx_symptom_history_urgency (urgency_level)
);
