apiVersion: v1
kind: Secret
metadata:
  name: smart-healthcare-secrets
  namespace: smart-healthcare
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "123456"
  MYSQL_AUTH_USERNAME: "auth_user"
  MYSQL_AUTH_PASSWORD: "auth_pass"
  MYSQL_DOCTOR_USERNAME: "doctor_user"
  MYSQL_DOCTOR_PASSWORD: "doctor_pass"
  MYSQL_PAYMENT_USERNAME: "payment_user"
  MYSQL_PAYMENT_PASSWORD: "payment_pass"
  MYSQL_NOTIFICATION_USERNAME: "notification_user"
  MYSQL_NOTIFICATION_PASSWORD: "notification_pass"
  MYSQL_TELEMEDICINE_USERNAME: "telemedicine_user"
  MYSQL_TELEMEDICINE_PASSWORD: "telemedicine_pass"
  MYSQL_AI_SUGGESTION_ROOT_PASSWORD: "root"
  APP_JWT_SECRET: "smart-healthcare-shared-jwt-secret-change-this-in-production-must-be-at-least-32-bytes"
  DOCTOR_SERVICE_USERNAME: "doctor"
  DOCTOR_SERVICE_PASSWORD: "doctor123"
  GEMINI_API_KEY: ""

