apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:8080
            - name: APPOINTMENT_SERVICE_URL
              value: http://appointment-service:8082
            - name: DOCTOR_SERVICE_URL
              value: http://doctor-service:8083
            - name: PATIENT_SERVICE_URL
              value: http://patient-service:8085
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification-service:8084
            - name: PAYMENT_SERVICE_URL
              value: http://payment-service:8086
            - name: TELEMEDICINE_SERVICE_URL
              value: http://telemedicine-service:8087
            - name: AI_DOCTOR_SUGGESTION_SERVICE_URL
              value: http://ai-doctor-suggestion-service:8092
            - name: AI_SYMPTOM_SERVICE_URL
              value: http://ai-symptom-service:8093
            - name: APP_SECURITY_ALLOWED_ORIGINS
              value: http://localhost:*,http://127.0.0.1:*
