apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-auth:3306/auth_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: auth_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: auth_pass
            - name: APP_JWT_SECRET
              value: smart-healthcare-shared-jwt-secret-change-this-in-production-must-be-at-least-32-bytes
            - name: APP_SECURITY_ALLOWED_ORIGINS
              value: http://localhost:*,http://127.0.0.1:*
            - name: SERVER_PORT
              value: "8080"
