apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
  namespace: smart-healthcare
  labels:
    app: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: smart-healthcare-microservices-y3s1_ds-telemedicine-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DOCKER_COMPOSE_ENABLED
              value: "false"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-telemedicine:3306/telemedicine_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smart-healthcare-secrets
                  key: MYSQL_TELEMEDICINE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smart-healthcare-secrets
                  key: MYSQL_TELEMEDICINE_PASSWORD
            - name: SERVER_PORT
              value: "8087"
          readinessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
  namespace: smart-healthcare
spec:
  type: ClusterIP
  selector:
    app: telemedicine-service
  ports:
    - name: http
      port: 8087
      targetPort: 8087

