services:
  mysql-telemedicine:
    image: mysql:8.0
    container_name: mysql-telemedicine-local
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: telemedicine_service_db
      MYSQL_USER: telemedicine_user
      MYSQL_PASSWORD: telemedicine_pass
    ports:
      - "3314:3306"
    volumes:
      - mysql-telemedicine-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql-telemedicine-data:
