services:
  mysql-auth:
    image: mysql:8.0
    container_name: mysql-auth-local
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: auth_service_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql-auth-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql-auth-data:
